Overriding model.yaml nc=80 with nc=2
                 from  n    params  module                                  arguments
  0                -1  1      5280  models.common.Conv                      [3, 48, 6, 2, 2]
  1                -1  1     41664  models.common.Conv                      [48, 96, 3, 2]
  2                -1  2     65280  models.common.C3                        [96, 96, 2]
  3                -1  1    166272  models.common.Conv                      [96, 192, 3, 2]
  4                -1  4    444672  models.common.C3                        [192, 192, 4]
  5                -1  1    664320  models.common.Conv                      [192, 384, 3, 2]
  6                -1  6   2512896  models.common.C3                        [384, 384, 6]
  7                -1  1   2655744  models.common.Conv                      [384, 768, 3, 2]
  8                -1  2   4134912  models.common.C3                        [768, 768, 2]
  9                -1  1   1476864  models.common.SPPF                      [768, 768, 5]
 10                -1  1    295680  models.common.Conv                      [768, 384, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  2   1182720  models.common.C3                        [768, 384, 2, False]
 14                -1  1     74112  models.common.Conv                      [384, 192, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  2    296448  models.common.C3                        [384, 192, 2, False]
 18                -1  1    332160  models.common.Conv                      [192, 192, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  2   1035264  models.common.C3                        [384, 384, 2, False]
 21                -1  1   1327872  models.common.Conv                      [384, 384, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  2   4134912  models.common.C3                        [768, 768, 2, False]
 24      [17, 20, 23]  1    755667  models.yolo.Detect                      [2, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [192, 384, 768]]
Model Summary: 369 layers, 21602739 parameters, 21602739 gradients, 50.4 GFLOPs
Transferred 475/481 items from weights/yolov5m.pt
Scaled weight_decay = 0.0005
[34m[1moptimizer:[39m[22m SGD with parameter groups 79 weight, 82 weight (no decay), 82 bias
[34m[1mtrain: [39m[22mScanning '/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/dataset/testspike/train/labelTxt.cache' images and labels... 254 found, 0 missing, 0 empty, 9 corrupted: 100% 254/254 [00:00<?, ?it/s]
[34m[1mtrain: [39m[22mWARNING: /media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/dataset/testspike/train/images/pic_DJI_0639_0003_11.jpg: ignoring corrupt image/label: negative label values [    -2.0578], please check your dota format labels
[34m[1mtrain: [39m[22mWARNING: /media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/dataset/testspike/train/images/pic_DJI_0639_0007_11.jpg: ignoring corrupt image/label: negative label values [   -0.70665], please check your dota format labels
[34m[1mtrain: [39m[22mWARNING: /media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/dataset/testspike/train/images/pic_DJI_0639_0007_12.jpg: ignoring corrupt image/label: negative label values [    -0.7056], please check your dota format labels
[34m[1mtrain: [39m[22mWARNING: /media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/dataset/testspike/train/images/pic_DJI_0639_0007_22.jpg: ignoring corrupt image/label: negative label values [    -3.6634], please check your dota format labels
[34m[1mtrain: [39m[22mWARNING: /media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/dataset/testspike/train/images/pic_DJI_0639_0021_21.jpg: ignoring corrupt image/label: negative label values [    -7.8452], please check your dota format labels
[34m[1mtrain: [39m[22mWARNING: /media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/dataset/testspike/train/images/pic_DJI_0639_0022_22.jpg: ignoring corrupt image/label: negative label values [   -0.64979], please check your dota format labels
[34m[1mtrain: [39m[22mWARNING: /media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/dataset/testspike/train/images/pic_DJI_0639_0055_21.jpg: ignoring corrupt image/label: negative label values [   -0.29858], please check your dota format labels
[34m[1mtrain: [39m[22mWARNING: /media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/dataset/testspike/train/images/pic_DJI_0639_0056_22.jpg: ignoring corrupt image/label: negative label values [    -11.004], please check your dota format labels
[34m[1mtrain: [39m[22mWARNING: /media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/dataset/testspike/train/images/pic_DJI_0639_0064_11.jpg: ignoring corrupt image/label: negative label values [    -1.9403], please check your dota format labels
[34m[1mval: [39m[22mScanning '/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/dataset/testspike/val/labelTxt.cache' images and labels... 10 found, 0 missing, 0 empty, 0 corrupted: 100% 10/10 [00:00<?, ?it/s]
Plotting labels to runs/train/exp45/labels_xyls.jpg...
[Errno 2] No such file or directory: 'runs/train/exp45/labels_correlogram.jpg'
[34m[1mAutoAnchor: [39m[22m2.06 anchors/target, 0.958 Best Possible Recall (BPR). Anchors are a poor fit to dataset ⚠️, attempting to improve...
[34m[1mAutoAnchor: [39m[22mWARNING: Extremely small objects found. 439 of 13037 poly labels are < 5 pixels in size.
[34m[1mAutoAnchor: [39m[22mRunning kmeans for 9 anchors on 13036 points...
[34m[1mAutoAnchor: [39m[22mEvolving anchors with Genetic Algorithm: fitness = 0.8038: 100% 1000/1000 [00:00<00:00, 1010.98it/s]
[34m[1mAutoAnchor: [39m[22mthr=0.25: 0.9998 best possible recall, 7.82 anchors past thr
[34m[1mAutoAnchor: [39m[22mn=9, img_size=1024, metric_all=0.481/0.804-mean/best, past_thr=0.525-mean: 23,6, 44,7, 36,12, 68,7, 64,11, 103,11, 69,18, 132,16, 128,32
[34m[1mAutoAnchor: [39m[22mNew anchors saved to model. Update model *.yaml to use these anchors in the future.
Image sizes 1024 train, 1024 val
Using 4 dataloader workers
Logging results to [1mruns/train/exp45
Starting training for 300 epochs...
     Epoch   gpu_mem       box       obj       cls     theta    labels  img_size
     0/299     4.07G    0.1328    0.3712   0.03045    0.7839       333      1024:   2% 1/62 [00:01<01:54,  1.88s/it]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/tensorboard/summary/writer/event_file_writer.py", line 233, in run
    self._record_writer.write(data)
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/tensorboard/summary/writer/record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 766, in write
    self.fs.append(self.filename, file_content, self.binary_mode)
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 160, in append
    self._write(filename, file_content, "ab" if binary_mode else "a")
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 164, in _write
    with io.open(filename, mode, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: b'runs/train/exp45/events.out.tfevents.1667309143.daaize.6794.0'
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/utils/plots.py", line 301, in plot_images
    annotator.im.save(fname)  # save
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/PIL/Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'runs/train/exp45/train_batch0.jpg'
     0/299     4.09G    0.1332    0.3219   0.03039    0.7856       252      1024:   3% 2/62 [00:03<01:40,  1.68s/it]Exception in thread Thread-16:
Traceback (most recent call last):
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/utils/plots.py", line 301, in plot_images
    annotator.im.save(fname)  # save
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/PIL/Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'runs/train/exp45/train_batch1.jpg'
     0/299     4.09G    0.1326    0.3463   0.03037    0.7849       342      1024:   5% 3/62 [00:04<01:28,  1.49s/it]Exception in thread Thread-17:
Traceback (most recent call last):
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/utils/plots.py", line 301, in plot_images
    annotator.im.save(fname)  # save
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/PIL/Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'runs/train/exp45/train_batch2.jpg'
     0/299      4.1G    0.1314    0.3178   0.03028    0.7853       286      1024:   8% 5/62 [00:07<01:14,  1.31s/it]Exception in thread Thread-19:
Traceback (most recent call last):
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/utils/plots.py", line 301, in plot_images
    annotator.im.save(fname)  # save
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/PIL/Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'runs/train/exp45/train_batch3.jpg'
     0/299      4.1G    0.1314    0.3178   0.03028    0.7853       286      1024:   8% 5/62 [00:07<01:14,  1.31s/it]Exception in thread Thread-19:
Traceback (most recent call last):
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/utils/plots.py", line 301, in plot_images
    annotator.im.save(fname)  # save
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/PIL/Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'runs/train/exp45/train_batch4.jpg'
     0/299      4.1G    0.1315    0.3245   0.03015    0.7848       319      1024:  10% 6/62 [00:08<01:13,  1.32s/it]Exception in thread Thread-20:
Traceback (most recent call last):
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/utils/plots.py", line 301, in plot_images
    annotator.im.save(fname)  # save
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/PIL/Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'runs/train/exp45/train_batch5.jpg'
     0/299      4.1G    0.1317    0.3439   0.03009    0.7846       443      1024:  11% 7/62 [00:09<01:15,  1.37s/it]
     0/299      4.1G    0.1317    0.3324   0.03008    0.7855       202      1024:  13% 8/62 [00:12<01:25,  1.59s/it]Exception in thread Thread-20:
     0/299      4.1G    0.1317    0.3324   0.03008    0.7855       202      1024:  13% 8/62 [00:12<01:25,  1.59s/it]Exception in thread Thread-22:
     0/299      4.1G    0.1317    0.3324   0.03008    0.7855       202      1024:  13% 8/62 [00:12<01:25,  1.59s/it]Exception in thread Thread-22:
     0/299      4.1G    0.1317    0.3324   0.03008    0.7855       202      1024:  13% 8/62 [00:12<01:25,  1.59s/it]Exception in thread Thread-22:
     0/299      4.1G    0.1317    0.3324   0.03008    0.7855       202      1024:  13% 8/62 [00:12<01:25,  1.59s/it]Exception in thread Thread-22:
     0/299      4.1G    0.1317    0.3324   0.03008    0.7855       202      1024:  13% 8/62 [00:12<01:25,  1.59s/it]Exception in thread Thread-22:
     0/299      4.1G    0.1317    0.3324   0.03008    0.7855       202      1024:  13% 8/62 [00:12<01:25,  1.59s/it]Exception in thread Thread-22:
     0/299      4.1G    0.1317    0.3324   0.03008    0.7855       202      1024:  13% 8/62 [00:12<01:25,  1.59s/it]Exception in thread Thread-22:
     0/299      4.1G    0.1317    0.3324   0.03008    0.7855       202      1024:  13% 8/62 [00:12<01:25,  1.59s/it]Exception in thread Thread-22:
     0/299      4.1G    0.1317    0.3324   0.03008    0.7855       202      1024:  13% 8/62 [00:12<01:25,  1.59s/it]Exception in thread Thread-22:
     0/299      4.1G    0.1317    0.3324   0.03008    0.7855       202      1024:  13% 8/62 [00:12<01:25,  1.59s/it]Exception in thread Thread-22:
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/train.py", line 654, in <module>.59s/it]Exception in thread Thread-22:
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/train.py", line 654, in <module>.59s/it]Exception in thread Thread-22:
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/train.py", line 654, in <module>.59s/it]Exception in thread Thread-22: