
WARNING: Dataset not found, nonexistent paths: ['/media/test/DOTA/DOTAv1.5/val_split_1024_gap200/images']
Traceback (most recent call last):
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/train.py", line 637, in <module>
    main(opt)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/train.py", line 534, in main
    train(opt.hyp, opt, device, callbacks)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/train.py", line 87, in train
    loggers = Loggers(save_dir, weights, opt, hyp, LOGGER)  # loggers instance
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/utils/loggers/__init__.py", line 76, in __init__
    self.wandb = WandbLogger(self.opt, run_id)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/utils/loggers/wandb/wandb_utils.py", line 180, in __init__
    self.data_dict = check_wandb_dataset(opt.data)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/utils/loggers/wandb/wandb_utils.py", line 56, in check_wandb_dataset
    return check_dataset(data_file)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/utils/general.py", line 418, in check_dataset
    raise Exception('Dataset not found.')
Exception: Dataset not found.